spring.application.name=inovatech

# Configurações do banco de dados
spring.datasource.url=jdbc:postgresql://localhost:5432/inovatech_db
spring.datasource.username=postgres
spring.datasource.password=123456

# Atualiza o esquema do banco de dados automaticamente
spring.jpa.hibernate.ddl-auto=update

# Exibir no terminal o SQL sendo executado
spring.jpa.show-sql=true

# Informa para não formatar o SQL
spring.jpa.properties.hibernate.format_sql=false

# Limpa o cache do Thymeleaf
spring.thymeleaf.cache=false

# Configurando o email
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=seuemail@gmail.com
spring.mail.password=senha_app
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Para limpar tokens expirados do banco de dados periodicamente.
purge.cron.expression=0 0 0 * * ?